version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building the JAR...
      - mvn clean package
      - echo Build complete.
  post_build:
    commands:
      - echo Build finished. JAR file should be in target/.
artifacts:
  files:
    - target/hello-world-docker-1.0-SNAPSHOT.jar
    - appspec.yml
    - Dockerfile
    - scripts/**  # includes all your shell scripts
